Script started on 2021-10-10 22:04:30-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="128" LINES="18"]
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ exit./q4exit[K./s[Karray
MAXIMUM AGE:
ID: A
Height: 74
Age: 23

MINIMUM AGE:
ID: C
Height: 68
Age: 19

MAXIMUM HEIGHT:
ID: D
Height: 76
Age: 20

MINIMUM HEIGHT:
ID: E
Height: 62
Age: 22

average age: 21
average height: 68
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ exit
exit

Script done on 2021-10-10 22:04:41-06:00 [COMMAND_EXIT_CODE="0"]
