Script started on 2021-10-10 22:03:23-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="128" LINES="18"]
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ ./q4
type 1 to enter a date
type 0 to quit
1
enter date in MM/DD/YY:  10/18/02
LIBRA
type 1 to enter a date
type 0 to quit
1 0
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ exit
exit

Script done on 2021-10-10 22:03:38-06:00 [COMMAND_EXIT_CODE="0"]
