Script started on 2021-10-10 22:07:52-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="128" LINES="18"]
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ ./lab5
size = 1474
max = 2116
min = 117
midpoint = 999
less than midpoint = 662
greater than midpoint = 812
midpoint not found in list
sum = 1615934
average = 1096
median = 1094
even count = 734
odd count = 740
count of divisible by minimum = 12
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ exit
exit

Script done on 2021-10-10 22:07:59-06:00 [COMMAND_EXIT_CODE="0"]
