Script started on 2021-10-10 22:01:54-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="128" LINES="18"]
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ ./q2
RED: 18
ORANGE: 19
YELLOW: 5
GREEN: 6
BLUE: 7
INDIGO: 14
VIOLET: 15
]0;gabraham@gabraham-VirtualBox: ~/cse113/lab 5/lab5[01;32mgabraham@gabraham-VirtualBox[00m:[01;34m~/cse113/lab 5/lab5[00m$ exit
exit

Script done on 2021-10-10 22:02:00-06:00 [COMMAND_EXIT_CODE="0"]
