Script started on 2022-03-09 19:27:46-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ gcc -g -Wall lab5_q2.c -o la b5_[K[K[K[Kb5_q2
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ ./lab5_q2
RED: 18
ORANGE: 19
YELLOW: 5
GREEN: 6
BLUE: 7
INDIGO: 14
VIOLET: 15
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ exit
exit

Script done on 2022-03-09 19:28:09-07:00 [COMMAND_EXIT_CODE="0"]
