Script started on 2022-03-09 17:39:49-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ gcc -g -Wall -c arrayc[K.c
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ gcc -g -Wall lab5.c array.o -o lab5
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ ./lab5
Size = 1474
Max = 2116
Min = 117
Midpoint = 999
Less than midpoint = 662
Greater than midpoint = 812
Midpoint not found in list
Sum = 1615934
Average = 1096
Median = 1094
Even count = 734
Odd count = 740
Count of divisible by min = 12
]0;mad@CSE113: ~/Desktop/lab5/lab5[01;32mmad@CSE113[00m:[01;34m~/Desktop/lab5/lab5[00m$ exit
exit

Script done on 2022-03-09 17:40:10-07:00 [COMMAND_EXIT_CODE="0"]
